export const navStyle = {
  grow: {
    position: "absolute",
    alignItems: "center",
    zIndex: 5,
    display: "flex",
    flexGrow: 1,
    boxShadow: "none",
    borderBottom: "2px solid #F3F3F5",
    backgroundColor: "#fff",
    margin: "0 auto",
    height: 60,
    width: 1200,
    left: 0,
    right: 0,
  },
  title: {
    textAlign: "center",
    width: 200,
    fontSize: 24,
    fontWeight: 700,
    fontStyle: "normal",
  },
  titleOnboarding: {
    display: "flex",
    position: "absolute",
    left: "46%",
    width: 500,
    fontSize: 24,
    fontWeight: 700,
    fontStyle: "normal",
  },
  search: {
    position: "relative",
    borderRadius: 8,
    backgroundColor: "#F3F3F5",
    margin: 0,
    height: 40,
    width: 300,
  },
  searchIcon: {
    height: "100%",
    position: "absolute",
    pointerEvents: "none",
    display: "flex",
    alignItems: "center",
    marginLeft: 5,
  },
  navbarBtns: {
    backgroundColor: "#F3F3F5",
    height: 40,
    width: 170,
    borderRadius: 24,
    marginLeft: 35,
    textTransform: "none",
  },
  skipText: {
    fontSize: 15,
    fontWeight: 400,
    fontStyle: "normal",
    color: "#7C7E8F",
    textTransform: "none",
  },
  editProfile: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 600,
    marginLeft: 180,
  },
  saveBtn: {
    fontSize: 15,
    fontWeight: 700,
    fontStyle: "normal",
    color: "#FA5821",
    marginLeft: 50,
  },
};
