export const sidebarStyle = {
  container: {
    display: "flex",
    position: "absolute",
    flexDirection: "column",
    borderWidth: 0,
    maxWidth: 400,
    margin: "0 auto",
    overflow: "auto",
    top: 450,
    webkitTransform: "translateY(-50%)",
    msTransform: "translateY(-50%)",
    transform: "translateY(-50%)",
  },
  policyText: {
    marginLeft: 7,
    fontSize: 13,
    fontWeight: 400,
    fontStyle: "normal",
    color: "#7C7E8F",
  },
  sidebarButton: {
    height: 52,
    width: 304,
    borderRadius: 50,
    textTransform: "none",
    justifyContent: "flex-start",
  },
  sideBarText: {
    fontStyle: "bold",
    fontWeight: 600,
    fontSize: 17,
    marginLeft: 23,
  },
  sidebarSocialIcon: {
    color: "#161931",
    marginBottom: 7,
    padding: 6,
    borderRadius: 50,
    border: "1px solid #B0B2BD",
  },
  policyContainer: {
    marginTop: 350,
  },
  projectNameText: {
    color: "#111235",
    fontSize: 12,
    fontWeight: 400,
    fontStyle: "normal",
    marginTop: 16,
    marginLeft: 7,
  },
};
