export const signUpStyle = {
  root: {
    display: "flex",
    flexDirection: "column",
    maxWidth: 800,
    width: "100%",
    margin: "0 auto",
    textAlign: "center",
  },
  textTitle: {
    fontSize: 24,
    fontStyle: "normal",
    fontWeight: 700,
    marginTop: 40,
    color: "#161931",
    textAlign: "center",
  },
  textDesclaimer: {
    fontSize: 17,
    fontStyle: "normal",
    color: "#7C7E8F",
    marginBottom: 5,
    marginTop: 20,
  },
  inputName: {
    maxWidth: 500,
    width: "100%",
    height: 52,
    marginTop: 10,
    borderRadius: 16,
  },
  errMessage: {
    maxWidth: 250,
    width: "100%",
    height: 22,
    marginLeft: 150,
    borderRadius: 16,
  },
  textButton: {
    fontSize: 15,
    fontStyle: "normal",
    color: "#fff",
    textTransform: "none",
  },
  nextButton: {
    backgroundColor: "#FA5821",
    marginTop: 30,
    borderRadius: 26,
    maxWidth: 480,
    width: "100%",
    height: 52,
    margin: "16px auto",
  },
  hasAccount: {
    marginLeft: 7,
    fontSize: 16,
    fontWeight: 700,
    color: "#FA5821",
    cursor: "pointer",
  },
};
