export const stepFourStyle = {
  main: {
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    top: 50,
    left: "35%",
  },
  grow: {
    flexGrow: 1,
    flexDirection: "row",
    display: "flex",
    alignItems: "center",
    width: 800,
    boxShadow: "none",
    borderBottom: "2px solid #F3F3F5",
    margin: "0 auto",
  },
  title: {
    display: "none",
    fontSize: 24,
    fontWeight: 700,
    marginLeft: 340,
  },
  subtitle: {
    fontSize: 15,
    fontWeight: 400,
    fontStyle: "normal",
    color: "#7C7E8F",
    marginBottom: 24,
  },
  skipText: {
    fontSize: 15,
    fontWeight: 400,
    fontStyle: "normal",
    color: "#7C7E8F",
    marginLeft: 120,
  },
  loadTitle: {
    fontSize: 24,
    fontWeight: 700,
    fontStyle: "normal",
    marginTop: 38,
  },
  block: {
    alignItems: "center",
    justifyContent: "center",
    display: "flex",
    flexDirection: "column",
  },
  loadButtons: {
    color: "white",
    borderRadius: 26,
    textTransform: "none",
    marginBottom: 5,
    width: 527,
    height: 52,
  },
  buttonsText: {
    fontSize: 17,
    fontWeight: 400,
    fontStyle: "normal",
    color: "#fff",
  },
  /* Next Button */
  nextButton: {
    backgroundColor: "#FA5821",
    color: "white",
    height: 52,
    width: 167,
    marginTop: 30,
    borderRadius: 26,
    textTransform: "none",
    textDecoration: "none",
  },
  nextBtnText: {
    textDecoration: "none",
    fontSize: 17,
    fontWeight: 600,
    fontStyle: "normal",
  },
};
