export const stepOneStyle = {
  grow: {
    flexGrow: 1,
    flexDirection: "row",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    boxShadow: "none",
    borderBottom: "2px solid #F3F3F5",
    margin: "0 auto",
    maxWidth: 800,
    width: "100%",
  },
  root: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    maxWidth: 800,
    width: "100%",
    margin: "0 auto",
  },
  title: {
    display: "none",
    fontSize: 24,
  },
  textTitle: {
    fontSize: 24,
    fontWeight: 700,
    marginTop: 40,
  },
  textDesclaimer: {
    fontSize: 15,
  },
  textButton: {
    fontSize: 17,
    fontStyle: "normal",
    color: "#fff",
    textTransform: "none",
  },
  emailButton: {
    backgroundColor: "#FA5821",
    borderRadius: 26,
    width: 528,
    height: 52,
    marginTop: 24,
  },
  textUnderButton: {
    fontSize: 13,
    fontWeight: 400,
    marginTop: 12,
    color: "#7C7E8F",
  },
  socialButtons: {
    width: 162,
    height: 52,
    borderRadius: 50,
    marginRight: 20,
    marginTop: 12,
  },
};
