export const stepFourStyle = {
  root: {
    textAlign: "center",
  },
  grow: {
    flexGrow: 1,
    flexDirection: "row",
    display: "flex",
    alignItems: "center",
    maxWidth: 800,
    width: "100%",
    boxShadow: "none",
    borderBottom: "2px solid #F3F3F5",
    margin: "0 auto",
  },
  subtitle: {
    fontSize: 15,
    fontStyle: "normal",
    color: "#7C7E8F",
    marginBottom: 24,
  },
  skipText: {
    fontSize: 15,
    fontWeight: 400,
    fontStyle: "normal",
    color: "#7C7E8F",
    marginLeft: 120,
  },
  loadTitle: {
    fontSize: 24,
    fontWeight: 700,
    fontStyle: "normal",
    marginTop: 38,
  },
  block: {
    alignItems: "center",
    justifyContent: "center",
    display: "flex",
    flexDirection: "column",
  },
  loadButtons: {
    color: "white",
    borderRadius: 26,
    textTransform: "none",
    margin: 8,
    maxWidth: 527,
    width: "100%",
    height: 52,
  },
  buttonsText: {
    fontSize: 17,
    fontStyle: "normal",
    color: "#fff",
  },
};
