export const headerStyle = {
  grow: {
    alignItems: "center",
    zIndex: 5,
    display: "flex",
    flexGrow: 1,
    boxShadow: "none",
    borderBottom: "2px solid #F3F3F5",
    backgroundColor: "#fff",
    margin: "0 auto",
    height: 60,
    maxWidth: 1200,
    width: "100%",
    left: 0,
    right: 0,
  },
  title: {
    maxWidth: 250,
    width: "100%",
    fontSize: 24,
    fontWeight: 700,
    fontStyle: "normal",
  },
  editProfile: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    maxWidth: 600,
    width: "100%",
    marginLeft: 180,
  },
  saveBtn: {
    fontSize: 15,
    fontWeight: 700,
    fontStyle: "normal",
    color: "#FA5821",
    marginLeft: 50,
  },
};
